<a href="https://colab.research.google.com/github/Pahan99/coursera/blob/main/tensorflow_devloper/C1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/Pahan99/coursera/tensorflow_devloper/C1.ipynb

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Flatten,Conv2D,MaxPooling2D

# Introduction

In [ ]:
model = Sequential([
    Dense(units=1, input_shape=[1])
])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='sgd',loss='mean_squared_error')

* `loss` is calculated and given to `optimizer` to figure out the next guess.

In [ ]:
X = np.array([x for x in range(-1,5)],dtype=float)
y = np.array([2*x-1 for x in X],dtype=float)
X,y

(array([-1.,  0.,  1.,  2.,  3.,  4.]), array([-3., -1.,  1.,  3.,  5.,  7.]))

In [ ]:
model.fit(X,y,epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 9ms/step - loss: 3.3409e-04
Epoch 2/100
1/1 [==============================] - 0s 9ms/step - loss: 3.2723e-04
Epoch 3/100
1/1 [==============================] - 0s 10ms/step - loss: 3.2050e-04
Epoch 4/100
1/1 [==============================] - 0s 9ms/step - loss: 3.1392e-04
Epoch 5/100
1/1 [==============================] - 0s 9ms/step - loss: 3.0747e-04
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 3.0116e-04
Epoch 7/100
1/1 [==============================] - 0s 8ms/step - loss: 2.9497e-04
Epoch 8/100
1/1 [==============================] - 0s 9ms/step - loss: 2.8891e-04
Epoch 9/100
1/1 [==============================] - 0s 7ms/step - loss: 2.8298e-04
Epoch 10/100
1/1 [==============================] - 0s 7ms/step - loss: 2.7716e-04
Epoch 11/100
1/1 [==============================] - 0s 6ms/step - loss: 2.7147e-04
Epoch 12/100
1/1 [==============================] - 0s 9ms/step - loss: 2.6590e-04
Epoch 13/100

In [ ]:
model.predict([10])

1/1 [==============================] - 0s 62ms/step


array([[18.980911]], dtype=float32)

# Introduction to Computer Vision

In [ ]:
fashion_mnist = tf.keras.datasets.fashion_mnist
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

X_train.shape, X_test.shape

4422102/4422102 [==============================] - 0s 0us/step


((60000, 28, 28), (10000, 28, 28))

In [ ]:
np.unique(y_train, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8),
 array([6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000]))

* Output has to contain 10 units.

In [ ]:
model = Sequential([
    Flatten(input_shape=(28,28)),
    Dense(units=128,activation='relu'),
    Dense(units=10,activation='softmax')
])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X_train,y_train,epochs=20)

Epoch 1/20
1875/1875 [==============================] - 10s 3ms/step - loss: 3.5717 - accuracy: 0.6992
Epoch 2/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.6934 - accuracy: 0.7539
Epoch 3/20
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5978 - accuracy: 0.7931
Epoch 4/20
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5335 - accuracy: 0.8157
Epoch 5/20
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5166 - accuracy: 0.8230
Epoch 6/20
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4920 - accuracy: 0.8326
Epoch 7/20
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4872 - accuracy: 0.8361
Epoch 8/20
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4848 - accuracy: 0.8377
Epoch 9/20
1875/1875 [==============================] - 5s 3ms/step - loss: 0.4748 - accuracy: 0.8400
Epoch 10/20
1875/1875 [==============================] - 5s 3ms/step - loss: 0.46

In [ ]:
model.evaluate(X_test,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.5705 - accuracy: 0.8301


[0.5705231428146362, 0.8300999999046326]

### Callbacks

* Can define a callback function to be evoked at each epoch.

In [ ]:
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs=None):
    if logs.get('loss') < 0.43:
      self.model.stop_training=True

In [ ]:
callback = myCallback()

model.fit(X_train,y_train,epochs=10, callbacks=[callback])

Epoch 1/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.4250 - accuracy: 0.8594


## CNN

In [ ]:
model = Sequential([
    Conv2D(filters=64,kernel_size=3,activation='relu',input_shape=(28,28,1)),
    MaxPooling2D(2,2),
    Conv2D(filters=64,kernel_size=3,activation='relu'),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(units=128,activation='relu'),
    Dense(units=10,activation='softmax')
])

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 64)        640       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 64)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        36928     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 flatten_1 (Flatten)         (None, 1600)              0         
                                                                 
 dense_2 (Dense)             (None, 128)              

In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X_train,y_train,epochs=20)

Epoch 1/20
1875/1875 [==============================] - 13s 3ms/step - loss: 0.5786 - accuracy: 0.8261
Epoch 2/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3367 - accuracy: 0.8754
Epoch 3/20
1875/1875 [==============================] - 7s 3ms/step - loss: 0.3003 - accuracy: 0.8878
Epoch 4/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2720 - accuracy: 0.8975
Epoch 5/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2526 - accuracy: 0.9043
Epoch 6/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2379 - accuracy: 0.9100
Epoch 7/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2193 - accuracy: 0.9176
Epoch 8/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2063 - accuracy: 0.9204
Epoch 9/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1950 - accuracy: 0.9268
Epoch 10/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.18

In [ ]:
model.evaluate(X_test,y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.6087 - accuracy: 0.8921


[0.6086759567260742, 0.8920999765396118]

# Real-world datasets

In [ ]:
fashion_mnist = tf.keras.datasets.fashion_mnist
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

X_train.shape, X_test.shape

4422102/4422102 [==============================] - 1s 0us/step


((60000, 28, 28), (10000, 28, 28))

# Image Data Generator

* Use directories to store images.

https://github.com/https-deeplearning-ai/tensorflow-1-public/blob/main/C1/W4/ungraded_labs/C1_W4_Lab_1_image_generator_no_validation.ipynb

In [3]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [ ]:
# All images will be rescaled by 1./255
train_datagen = ImageDataGenerator(rescale=1/255)
validation_datagen = ImageDataGenerator(rescale=1/255)

# Flow training images in batches of 128 using train_datagen generator
train_generator = train_datagen.flow_from_directory(
        './horse-or-human/',  # This is the source directory for training images
        target_size=(150, 150),  # All images will be resized to 150x150
        batch_size=128,
        # Since you used binary_crossentropy loss, you need binary labels
        class_mode='binary')

# Flow training images in batches of 128 using train_datagen generator
validation_generator = validation_datagen.flow_from_directory(
        './validation-horse-or-human/',  # This is the source directory for training images
        target_size=(150, 150),  # All images will be resized to 150x150
        batch_size=32,
        # Since you used binary_crossentropy loss, you need binary labels
        class_mode='binary')